export const translations_en = {
  "TKodyKrajowUE.AT": "AUSTRIA",
  "TKodyKrajowUE.BE": "BELGIUM",
  "TKodyKrajowUE.BG": "BULGARIA",
  "TKodyKrajowUE.CY": "CYPRUS",
  "TKodyKrajowUE.CZ": "THE CZECH REPUBLIC",
  "TKodyKrajowUE.DK": "DENMARK",
  "TKodyKrajowUE.EE": "ESTONIA",
  "TKodyKrajowUE.FI": "FINLAND",
  "TKodyKrajowUE.FR": "FRANCE",
  "TKodyKrajowUE.DE": "GERMANY",
  "TKodyKrajowUE.EL": "GREECE",
  "TKodyKrajowUE.HR": "CROATIA",
  "TKodyKrajowUE.HU": "HUNGARY",
  "TKodyKrajowUE.IE": "IRELAND",
  "TKodyKrajowUE.IT": "ITALY",
  "TKodyKrajowUE.LV": "LATVIA",
  "TKodyKrajowUE.LT": "LITHUANIA",
  "TKodyKrajowUE.LU": "LUXEMBOURG",
  "TKodyKrajowUE.MT": "Malt",
  "TKodyKrajowUE.NL": "NETHERLANDS",
  "TKodyKrajowUE.PL": "POLAND",
  "TKodyKrajowUE.PT": "PORTUGAL",
  "TKodyKrajowUE.RO": "ROMANIA",
  "TKodyKrajowUE.SK": "SLOVAKIA",
  "TKodyKrajowUE.SI": "SLOVENIA",
  "TKodyKrajowUE.ES": "SPAIN",
  "TKodyKrajowUE.SE": "SWEDEN",
  "TKodyKrajowUE.XI": "Northern Ireland",
  "TKodWaluty.AED": "Dirham Zea",
  "TKodWaluty.AFN": "Afghan",
  "TKodWaluty.ALL": "BOW",
  "TKodWaluty.AMD": "Drama",
  "TKodWaluty.ANG": "Gulden Antiles of Dutch",
  "TKodWaluty.AOA": "Quanza",
  "TKodWaluty.ARS": "Argentine peso",
  "TKodWaluty.AUD": "Australian dollar",
  "TKodWaluty.AWG": "Aruba Gulden",
  "TKodWaluty.AZN": "Azerbaijan manat",
  "TKodWaluty.BAM": "Spare brand",
  "TKodWaluty.BBD": "Barbados dollar",
  "TKodWaluty.BDT": "Such",
  "TKodWaluty.BGN": "LION",
  "TKodWaluty.BHD": "Dinar Bahrajski",
  "TKodWaluty.BIF": "Frank Burundian",
  "TKodWaluty.BMD": "Bermuda dollar",
  "TKodWaluty.BND": "Dollar Brune",
  "TKodWaluty.BOB": "Boliviano",
  "TKodWaluty.BOV": "Boliviano MVDOL",
  "TKodWaluty.BRL": "REAL",
  "TKodWaluty.BSD": "Dollar Bahama",
  "TKodWaluty.BTN": "Ngultrum",
  "TKodWaluty.BWP": "POOL",
  "TKodWaluty.BYN": "Belarusian ruble",
  "TKodWaluty.BZD": "Belize dollar",
  "TKodWaluty.CAD": "Canadian dollar",
  "TKodWaluty.CDF": "Congress Frank",
  "TKodWaluty.CHE": "Swiss franc vir euro",
  "TKodWaluty.CHF": "Swiss franc",
  "TKodWaluty.CHW": "Swiss franc vir frank",
  "TKodWaluty.CLF": "Chilean settlement unit",
  "TKodWaluty.CLP": "Chilean peso",
  "TKodWaluty.CNY": "Yuan Renminbi",
  "TKodWaluty.COP": "Colombian peso",
  "TKodWaluty.COU": "Unidad de Valor Real Colombils",
  "TKodWaluty.CRC": "Colon Costa Rica",
  "TKodWaluty.CUC": "Convertible peso",
  "TKodWaluty.CUP": "Cuban peso",
  "TKodWaluty.CVE": "Escudo of the Cape Verde",
  "TKodWaluty.CZK": "Czech crown",
  "TKodWaluty.DJF": "Frank Djibuti",
  "TKodWaluty.DKK": "Danish crown",
  "TKodWaluty.DOP": "Dominican peso",
  "TKodWaluty.DZD": "Algerian Dinar",
  "TKodWaluty.EGP": "Egyptian pound",
  "TKodWaluty.ERN": "Nutra",
  "TKodWaluty.ETB": "Birr",
  "TKodWaluty.EUR": "EURO",
  "TKodWaluty.FJD": "Dollar fiji",
  "TKodWaluty.FKP": "Falkland pound",
  "TKodWaluty.GBP": "STERLING",
  "TKodWaluty.GEL": "LARI",
  "TKodWaluty.GGP": "Pound guernsey",
  "TKodWaluty.GHS": "Ghana Cedi",
  "TKodWaluty.GIP": "Pound of gibraltarski",
  "TKodWaluty.GMD": "Long",
  "TKodWaluty.GNF": "Guinean Frank",
  "TKodWaluty.GTQ": "Quetzal",
  "TKodWaluty.GYD": "Guinean dollar",
  "TKodWaluty.HKD": "Hong Kong dollar",
  "TKodWaluty.HNL": "Lempir",
  "TKodWaluty.HRK": "MARTEN",
  "TKodWaluty.HTG": "Gourde",
  "TKodWaluty.HUF": "Forint",
  "TKodWaluty.IDR": "Indonesian rupe",
  "TKodWaluty.ILS": "SHEKEL",
  "TKodWaluty.IMP": "Pound manx",
  "TKodWaluty.INR": "Indian rupe",
  "TKodWaluty.IQD": "Iraqi Dinar",
  "TKodWaluty.IRR": "Iranian Rial",
  "TKodWaluty.ISK": "Icelandic crown",
  "TKodWaluty.JEP": "Pound jersey",
  "TKodWaluty.JMD": "Jamaican dollar",
  "TKodWaluty.JOD": "Jordan Dinar",
  "TKodWaluty.JPY": "YEN",
  "TKodWaluty.KES": "Kenyan shilling",
  "TKodWaluty.KGS": "SOM",
  "TKodWaluty.KHR": "Riel",
  "TKodWaluty.KMF": "Frank Komorów",
  "TKodWaluty.KPW": "North Korean won",
  "TKodWaluty.KRW": "South Korean fragrances",
  "TKodWaluty.KWD": "Dinar Kuwait",
  "TKodWaluty.KYD": "Kajmański dollar",
  "TKodWaluty.KZT": "Tege",
  "TKodWaluty.LAK": "Kip",
  "TKodWaluty.LBP": "Lebanese pound",
  "TKodWaluty.LKR": "Lankan rupe",
  "TKodWaluty.LRD": "Liberian dollar",
  "TKodWaluty.LSL": "Flight",
  "TKodWaluty.LYD": "Libyan Dinar",
  "TKodWaluty.MAD": "Dirham Moroccan",
  "TKodWaluty.MDL": "Lej Moldova",
  "TKodWaluty.MGA": "Ariar",
  "TKodWaluty.MKD": "DENARIUS",
  "TKodWaluty.MMK": "Kyat",
  "TKodWaluty.MNT": "Tugrik",
  "TKodWaluty.MOP": "Patac",
  "TKodWaluty.MRU": "Ouguiya",
  "TKodWaluty.MUR": "Rupia Mauritiusu",
  "TKodWaluty.MVR": "Maldiwska Rupia",
  "TKodWaluty.MWK": "Malawian kwacha",
  "TKodWaluty.MXN": "Mexican peso",
  "TKodWaluty.MXV": "Unidad de Inversion (Udi) Mexican",
  "TKodWaluty.MYR": "Ringgit",
  "TKodWaluty.MZN": "Metical",
  "TKodWaluty.NAD": "Namibian dollar",
  "TKodWaluty.NGN": "Naira",
  "TKodWaluty.NIO": "Cordoba ORO",
  "TKodWaluty.NOK": "Norwegian crown",
  "TKodWaluty.NPR": "Nepalese rupe",
  "TKodWaluty.NZD": "New Zealand dollar",
  "TKodWaluty.OMR": "Rial Oman",
  "TKodWaluty.PAB": "Balboa",
  "TKodWaluty.PEN": "SALT",
  "TKodWaluty.PGK": "Cinema",
  "TKodWaluty.PHP": "Filipino peso",
  "TKodWaluty.PKR": "Pakistani rupe",
  "TKodWaluty.PLN": "GOLDEN",
  "TKodWaluty.PYG": "Guarans",
  "TKodWaluty.QAR": "Catches",
  "TKodWaluty.RON": "Romanian funnel",
  "TKodWaluty.RSD": "Dinar Serbian",
  "TKodWaluty.RUB": "Russian ruble",
  "TKodWaluty.RWF": "Frank Rwanda",
  "TKodWaluty.SAR": "Saudi Rial",
  "TKodWaluty.SBD": "Dollar of the Solomon Islands",
  "TKodWaluty.SCR": "Seychelled rupe",
  "TKodWaluty.SDG": "Suda pound",
  "TKodWaluty.SEK": "Swedish crown",
  "TKodWaluty.SGD": "Singapore dollar",
  "TKodWaluty.SHP": "Pound of Saint Helena (Saint Helena and the island of ascension)",
  "TKodWaluty.SLL": "Leone",
  "TKodWaluty.SOS": "Somali shilling",
  "TKodWaluty.SRD": "Surinam dollar",
  "TKodWaluty.SSP": "South Slavic Pound",
  "TKodWaluty.STN": "ALL RIGHT",
  "TKodWaluty.SVC": "Colon Salvadorski (SV1)",
  "TKodWaluty.SYP": "Syrian pound",
  "TKodWaluty.SZL": "Lilane",
  "TKodWaluty.THB": "WHIP",
  "TKodWaluty.TJS": "Somoni",
  "TKodWaluty.TMT": "Turkmen manat",
  "TKodWaluty.TND": "Tunisian dinar",
  "TKodWaluty.TOP": "Paang",
  "TKodWaluty.TRY": "Turkish lira",
  "TKodWaluty.TTD": "Dollar of Trinidad and Tobago",
  "TKodWaluty.TWD": "New Taiwan dollar",
  "TKodWaluty.TZS": "Tanzanian shilling",
  "TKodWaluty.UAH": "Hryon",
  "TKodWaluty.UGX": "Ugandian shilling",
  "TKodWaluty.USD": "American dollar",
  "TKodWaluty.USN": "American dollar (Next Day)",
  "TKodWaluty.UYI": "Peso en unidades indexadas uruguayan",
  "TKodWaluty.UYU": "Uruguayan peso",
  "TKodWaluty.UYW": "Peso en unidades indexadas uruguayan",
  "TKodWaluty.UZS": "CATFISH",
  "TKodWaluty.VES": "Soberano bolivar",
  "TKodWaluty.VND": "Dong",
  "TKodWaluty.VUV": "VAT",
  "TKodWaluty.WST": "Tala",
  "TKodWaluty.XAF": "Frank cfa (beac)",
  "TKodWaluty.XAG": "SILVER",
  "TKodWaluty.XAU": "GOLD",
  "TKodWaluty.XBA": "Bond Markets Unit European Composite Unit (Eurco)",
  "TKodWaluty.XBB": "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
  "TKodWaluty.XBC": "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
  "TKodWaluty.XBD": "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
  "TKodWaluty.XCD": "East -Law Dollar",
  "TKodWaluty.XDR": "SDR International Monetary Fund",
  "TKodWaluty.XOF": "Frank CFA (BCEAO)",
  "TKodWaluty.XPD": "Palladium",
  "TKodWaluty.XPF": "Frank CFP",
  "TKodWaluty.XPT": "PLATINUM",
  "TKodWaluty.XSU": "Sucre Sister Unitario de Compensacion Regional de Pagos Sucre",
  "TKodWaluty.XUA": "Adb Unit of Account Member Countries of the African Development Bank Group",
  "TKodWaluty.XXX": "No currency",
  "TKodWaluty.YER": "Yemenian Rial",
  "TKodWaluty.ZAR": "Rand",
  "TKodWaluty.ZMW": "Kwaca Zambian",
  "TKodWaluty.ZWL": "Dollar Zimbabwe",
  "TFormaPlatnosci.1": "Cash",
  "TFormaPlatnosci.2": "Card",
  "TFormaPlatnosci.3": "Bon",
  "TFormaPlatnosci.4": "Check",
  "TFormaPlatnosci.5": "Loan",
  "TFormaPlatnosci.6": "Transfer",
  "TFormaPlatnosci.7": "Mobile",
  "TLadunek.1": "Bubble",
  "TLadunek.2": "Barrel",
  "TLadunek.3": "Cylinder",
  "TLadunek.4": "Cardboard",
  "TLadunek.5": "Canister",
  "TLadunek.6": "Cage",
  "TLadunek.7": "Container",
  "TLadunek.8": "Basket/basket",
  "TLadunek.9": "Lubble",
  "TLadunek.10": "Collective packaging",
  "TLadunek.11": "Package",
  "TLadunek.12": "Package",
  "TLadunek.13": "Palette",
  "TLadunek.14": "Container",
  "TLadunek.15": "CONTAINER FOR MASTLE CARDES",
  "TLadunek.16": "Container for mass loads in liquid form",
  "TLadunek.17": "Box",
  "TLadunek.18": "Can",
  "TLadunek.19": "Chest",
  "TLadunek.20": "Bag",
  "TRachunekWlasnyBanku.1": "Bank account or account of the Cooperative Savings and Credit Office used to make settlements for the bank purchased by this bank or this Fund",
  "TRachunekWlasnyBanku.2": "Bank's account or account of the Cooperative Savings and Credit Office used by this bank or this cash register to download from the buyer of goods or the Service Recipient for the supply of goods or the provision of services, confirmed by the invoice, and transfer it in whole or part of the provider of goods or service providers in whole or part of the provider",
  "TRachunekWlasnyBanku.3": "Bank account or account of the Cooperative Savings and Credit Office kept by this bank or this money as part of its own economy, which is not a billing account",
  "TStatusInfoPodatnika.1": "A taxpayer in a state of liquidation",
  "TStatusInfoPodatnika.2": "A taxpayer who is undergoing restructuring proceedings",
  "TStatusInfoPodatnika.3": "A taxpayer in a state of bankruptcy",
  "TStatusInfoPodatnika.4": "Company inheritance",
  "TRolaPodmiotuUpowaznionego.1": "The enforcement authority - in the case referred to in art. 106c point 1 of the Act",
  "TRolaPodmiotuUpowaznionego.2": "Court bailiff - in the case referred to in art. 106c point 2 of the Act",
  "TRolaPodmiotuUpowaznionego.3": "A tax representative - in the event that the invoice has a given tax representative referred to in the provisions of art. 18a - 18d of the Act",
  "TRolaPodmiotu3.1": "Factor - if the invoice has a factor's data",
  "TRolaPodmiotu3.2": "The recipient - in the event that the invoice has data of internal units, branches separated as part of the buyer, which themselves do not constitute the buyer within the meaning of the Act",
  "TRolaPodmiotu3.3": "A primary entity - in the event that the invoice has the data of the entity being in relation to the taxpayer with an acquired or transformed entity, which provided the service or made delivery. Excluding the cases referred to in art. 106J para",
  "TRolaPodmiotu3.4": "Additional buyer - in the event that the invoice has subsequent data (other than mentioned in the part of the entity2) buyers",
  "TRolaPodmiotu3.5": "Invoice issuer - in the event that the invoice has data of the entity issuing the invoice on behalf of the taxpayer. Does not apply to the case when the invoice exhibitor is the buyer",
  "TRolaPodmiotu3.6": "Making payments - in the event that the invoice has data of the entity governing the obligation in place of the buyer",
  "TRolaPodmiotu3.7": "Local government unit - exhibitor",
  "TRolaPodmiotu3.8": "Local government unit - recipient",
  "TRolaPodmiotu3.9": "Member of the VAT group - exhibitor",
  "TRolaPodmiotu3.10": "Member of the VAT group - recipient",
  "TRodzajFaktury.VAT": "Basic invoice",
  "TRodzajFaktury.KOR": "Correcting texture",
  "TRodzajFaktury.ZAL": "An invoice documenting the receipt of payment or part of it before making activities and an invoice issued in connection with art. 106f para. 4 of the Act",
  "TRodzajFaktury.ROZ": "An invoice issued in connection with art. 106f para. 3 of the Act",
  "TRodzajFaktury.UPR": "The invoice referred to in art. 106e para. 5 point 3 of the Act",
  "TRodzajFaktury.KOR_ZAL": "An invoice correcting the invoice documenting the receipt of payment or part of it before making the act and the invoice issued in connection with art. 106f para. 4 of the Act",
  "TRodzajFaktury.KOR_ROZ": "An invoice correcting the invoice issued in connection with art. 106f para. 3 of the Act",
  "TTypKorekty.1": "Correction resulting in the date of the primary invoice",
  "TTypKorekty.2": "Correction resulting in the date of issuing a corrective invoice",
  "TTypKorekty.3": "Correction resulting in a different date, including when for different items of the corrective invoice these dates are different",
  "TStawkaPodatku.zw": "tax exempt",
  "TStawkaPodatku.oo": "reverse load",
  "TStawkaPodatku.np": "not subject to taxation- delivery of goods and the provision of services outside the territory of the country",
  "TOznaczenieProcedury.WSTO_EE": "The designation regarding the procedure referred to in § 10 para. 4 point 2a of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProcedury.IED": "The designation regarding the procedure referred to in § 10 para. 4 point 2b of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProcedury.TT_D": "The designation regarding the procedure referred to in § 10 para. 4 point 5 of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProcedury.I_42": "The designation regarding the procedure referred to in § 10 para. 4 point 8 of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProcedury.I_63": "The designation regarding the procedure referred to in § 10 para. 4 point 9 of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProcedury.B_SPV": "The designation regarding the procedure referred to in § 10 para. 4 point 10 of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProcedury.B_SPV_DOSTAWA": "The designation regarding the procedure referred to in § 10 para. 4 point 11 of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProcedury.B_MPV_PROWIZJA": "The designation regarding the procedure referred to in § 10 para. 4 point 12 of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProceduryZ.WSTO_EE": "The designation regarding the procedure referred to in § 10 para. 4 point 2a of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProceduryZ.IED": "The designation regarding the procedure referred to in § 10 para. 4 point 2b of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProceduryZ.TT_D": "The designation regarding the procedure referred to in § 10 para. 4 point 5 of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProceduryZ.B_SPV": "The designation regarding the procedure referred to in § 10 para. 4 point 10 of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProceduryZ.B_SPV_DOSTAWA": "The designation regarding the procedure referred to in § 10 para. 4 point 11 of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TOznaczenieProceduryZ.B_MPV_PROWIZJA": "The designation regarding the procedure referred to in § 10 para. 4 point 12 of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_01": "Delivery of goods referred to in § 10 para. 3 point 1 lit. a regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_02": "Delivery of goods referred to in § 10 para. 3 point 1 lit. b of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_03": "Delivery of goods referred to in § 10 para. 3 point 1 lit. c of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_04": "Delivery of goods referred to in § 10 para. 3 point 1 lit. d of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_05": "Delivery of goods referred to in § 10 para. 3 point 1 lit. e of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_06": "Delivery of goods referred to in § 10 para. 3 point 1 lit. f of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_07": "Delivery of goods referred to in § 10 para. 3 point 1 lit. G of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_08": "Delivery of goods referred to in § 10 para. 3 point 1 lit. h of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_09": "Delivery of goods referred to in § 10 para. 3 point 1 lit. and the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_10": "Delivery of goods referred to in § 10 para. 3 point 1 lit. j of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_11": "The provision of services referred to in § 10 para. 3 point 2 lit. a regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_12": "The provision of services referred to in § 10 para. 3 point 2 lit. b of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TGTU.GTU_13": "The provision of services referred to in § 10 para. 3 point 2 lit. c of the Regulation on the detailed scope of data contained in tax declarations and in the records in the field of tax on goods and services",
  "TRodzajTransportu.1": "Sea transport",
  "TRodzajTransportu.2": "Rail",
  "TRodzajTransportu.3": "Road transport",
  "TRodzajTransportu.4": "Air transport",
  "TRodzajTransportu.5": "Postal shipment",
  "TRodzajTransportu.7": "Permanent transmission installations",
  "TRodzajTransportu.8": "Inland navigation",
};
